title: 罗会祥的博客
email: 2437844933@qq.com
description: 这是我的个人博客,主要分享一些平时学习工作中遇到的问题和一些心得
baseurl: ""
url: "http://yourdomain.com"
github: "https://github.com/lancebiu"
weibo: "http://weibo.com/u/5337869639"
email: "2437844933@qq.com"

paginate: 8

markdown: kramdown
